package com.demo2.models;
// Generated 19/05/2018 03:04:13 PM by Hibernate Tools 4.3.1



/**
 * PacienteAlumno generated by hbm2java
 */
public class PacienteAlumno  implements java.io.Serializable {


     private int dniAlumno;
     private Integer codigoAlumno;
     private String nombresAlumno;
     private String apellidosAlumno;
     private String facultad;
     private String escuela;
     private String sexo;
     private String telefono;
     private String direccion;
     private Integer tipoDescuento;

    public PacienteAlumno() {
    }

	
    public PacienteAlumno(int dniAlumno) {
        this.dniAlumno = dniAlumno;
    }
    public PacienteAlumno(int dniAlumno, Integer codigoAlumno, String nombresAlumno, String apellidosAlumno, String facultad, String escuela, String sexo, String telefono, String direccion, Integer tipoDescuento) {
       this.dniAlumno = dniAlumno;
       this.codigoAlumno = codigoAlumno;
       this.nombresAlumno = nombresAlumno;
       this.apellidosAlumno = apellidosAlumno;
       this.facultad = facultad;
       this.escuela = escuela;
       this.sexo = sexo;
       this.telefono = telefono;
       this.direccion = direccion;
       this.tipoDescuento = tipoDescuento;
    }
   
    public int getDniAlumno() {
        return this.dniAlumno;
    }
    
    public void setDniAlumno(int dniAlumno) {
        this.dniAlumno = dniAlumno;
    }
    public Integer getCodigoAlumno() {
        return this.codigoAlumno;
    }
    
    public void setCodigoAlumno(Integer codigoAlumno) {
        this.codigoAlumno = codigoAlumno;
    }
    public String getNombresAlumno() {
        return this.nombresAlumno;
    }
    
    public void setNombresAlumno(String nombresAlumno) {
        this.nombresAlumno = nombresAlumno;
    }
    public String getApellidosAlumno() {
        return this.apellidosAlumno;
    }
    
    public void setApellidosAlumno(String apellidosAlumno) {
        this.apellidosAlumno = apellidosAlumno;
    }
    public String getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(String facultad) {
        this.facultad = facultad;
    }
    public String getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(String escuela) {
        this.escuela = escuela;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getTipoDescuento() {
        return this.tipoDescuento;
    }
    
    public void setTipoDescuento(Integer tipoDescuento) {
        this.tipoDescuento = tipoDescuento;
    }




}


